kind: pipeline
name: default

steps:
- name: apply ansible playbook
  image: plugins/ansible:1
  settings:
    playbook: /aws-files/ansible/net_init_deploy.yml
    inventory: /aws-files/ansible/inventory
  when:
    event:
    - push
    - tag
