--- # Change Hostname
- hosts: R1
  gather_facts: false
  connection: network_cli
  become: yes
  become_method: enable

  tasks:
   - name: Hostname setting
     ios_config:
       lines:
         - hostname Router1
         - do wr

- hosts: R2
  gather_facts: false
  connection: network_cli
  become: yes
  become_method: enable

  tasks:
   - name: Hostname setting
     ios_config:
       lines:
         - hostname Router2
         - do wr

- hosts: R3
  gather_facts: false
  connection: network_cli
  become: yes
  become_method: enable

  tasks:
   - name: Hostname setting
     ios_config:
       lines:
         - hostname Router3
         - do wr
