--- # Change Hostname
- hosts: R1
  gather_facts: false
  connection: network_cli
  become: yes
  become_method: enable

  tasks:
   - name: Hostname setting
     ios_config:
       lines:
         - hostname Router1
         - do wr
