---
- name: Enable HTTP Server on all Routers
  hosts: routers
  connection: local
  gather_facts: false

  roles:
    - ios_http_server



# - name: Configure Syslog on all Routers
#   hosts: routers
#   connection: local
#   gather_facts: false
#
#   roles:
#     - iosxe_mdp
