---
- name: Enable HTTP Server on all Routers
  hosts: routers
  connection: local
  gather_facts: false

  roles:
    - ios_http_server

- name: Configure NTP Servers on all Routers
  hosts: routers
  connection: local
  gather_facts: false

  roles:
    - ios_ntp
